// GENERATED from unchanged origin/main (fdc94e41) by the two-tree WES2 parity
// harness. Each value: setCount#set|set…, a set = weight;reps;rir and each
// field = actual,hint,origin,hintOrigin. Selected dates carry NO same-day
// history (the strict-before rule is the one approved ordinary-WES2 change).
// Do not edit by hand.

const Map<String, String> kOriginMainGolden = <String, String>{
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-07|none":
      "5#-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-07|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-13|none":
      "5#-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.25,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.5,modelHint,modelHint|-,80,modelHint,modelHint;-,9,modelHint,modelHint;-,1.75,modelHint,modelHint|-,80,modelHint,modelHint;-,9,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-13|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-25|none":
      "5#-,110,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,105,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,4,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint|-,85,modelHint,modelHint;-,9,modelHint,modelHint;-,4,modelHint,modelHint|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-25|s1:rir":
      "5#-,82.5,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,77.5,modelHint,modelHint;-,11,modelHint,modelHint;-,3.5,modelHint,modelHint|-,72.5,modelHint,modelHint;-,12,modelHint,modelHint;-,4,modelHint,modelHint|-,67.5,modelHint,modelHint;-,13,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|Smart Progression|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,4,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-07|none":
      "5#-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-07|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-13|none":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-13|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-25|none":
      "5#-,107.5,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,4,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,4,modelHint,modelHint|-,80,modelHint,modelHint;-,9,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-25|s1:rir":
      "5#-,80,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,75,modelHint,modelHint;-,11,modelHint,modelHint;-,3.5,modelHint,modelHint|-,70,modelHint,modelHint;-,12,modelHint,modelHint;-,4,modelHint,modelHint|-,65,modelHint,modelHint;-,13,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Exposure|None|2026-01-25|s1:r+rir":
      "5#-,100,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,4,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-07|none":
      "5#-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-07|s1:rir":
      "5#-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-13|none":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-13|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-25|none":
      "5#-,102.5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.5,modelHint,modelHint|-,97.5,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-25|s1:rir":
      "5#-,107.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,107.5,modelHint,modelHint;-,3,modelHint,modelHint;-,3,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|Smart Progression|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-07|none":
      "5#-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-07|s1:rir":
      "5#-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-13|none":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-13|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-25|none":
      "5#-,102.5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.5,modelHint,modelHint|-,97.5,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-25|s1:rir":
      "5#-,107.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,107.5,modelHint,modelHint;-,3,modelHint,modelHint;-,3,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, Signature|None|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-07|none":
      "5#-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-07|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-13|none":
      "5#-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.25,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.5,modelHint,modelHint|-,80,modelHint,modelHint;-,9,modelHint,modelHint;-,1.75,modelHint,modelHint|-,80,modelHint,modelHint;-,9,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-13|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-25|none":
      "5#-,110,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,105,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,4,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,8,modelHint,modelHint;-,3.5,modelHint,modelHint|-,85,modelHint,modelHint;-,9,modelHint,modelHint;-,4,modelHint,modelHint|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-25|s1:rir":
      "5#-,82.5,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,77.5,modelHint,modelHint;-,11,modelHint,modelHint;-,3.5,modelHint,modelHint|-,72.5,modelHint,modelHint;-,12,modelHint,modelHint;-,4,modelHint,modelHint|-,67.5,modelHint,modelHint;-,13,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|Smart Progression|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,4,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-07|none":
      "5#-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,0.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-07|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-13|none":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-13|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-25|none":
      "5#-,107.5,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,4,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,3.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,4,modelHint,modelHint|-,80,modelHint,modelHint;-,9,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-25|s1:rir":
      "5#-,80,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,75,modelHint,modelHint;-,11,modelHint,modelHint;-,3.5,modelHint,modelHint|-,70,modelHint,modelHint;-,12,modelHint,modelHint;-,4,modelHint,modelHint|-,65,modelHint,modelHint;-,13,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|DUP, By Week|None|2026-01-25|s1:r+rir":
      "5#-,100,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,3.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,4,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-07|none":
      "5#-,75,modelHint,modelHint;-,12,modelHint,modelHint;-,0.3,modelHint,modelHint|-,70,modelHint,modelHint;-,13,modelHint,modelHint;-,0.75,modelHint,modelHint|-,65,modelHint,modelHint;-,14,modelHint,modelHint;-,1.25,modelHint,modelHint|-,60,modelHint,modelHint;-,15,modelHint,modelHint;-,1.75,modelHint,modelHint|-,55,modelHint,modelHint;-,16,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-07|s1:rir":
      "5#-,100,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-07|s1:r+rir":
      "5#-,90,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.25,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.75,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-13|none":
      "5#-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,1,modelHint,modelHint|-,75,modelHint,modelHint;-,12,modelHint,modelHint;-,1.25,modelHint,modelHint|-,70,modelHint,modelHint;-,13,modelHint,modelHint;-,1.5,modelHint,modelHint|-,65,modelHint,modelHint;-,14,modelHint,modelHint;-,1.75,modelHint,modelHint|-,65,modelHint,modelHint;-,14,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-13|s1:rir":
      "5#-,95,modelHint,modelHint;-,6,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-13|s1:r+rir":
      "5#-,95,modelHint,modelHint;6,6,typed,modelHint;1.5,-,typed,empty|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-25|none":
      "5#-,110,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,105,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,105,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,105,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,105,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-25|s1:rir":
      "5#-,82.5,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|Smart Progression|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-07|none":
      "5#-,75,modelHint,modelHint;-,12,modelHint,modelHint;-,0.3,modelHint,modelHint|-,70,modelHint,modelHint;-,13,modelHint,modelHint;-,0.75,modelHint,modelHint|-,65,modelHint,modelHint;-,14,modelHint,modelHint;-,1.25,modelHint,modelHint|-,60,modelHint,modelHint;-,15,modelHint,modelHint;-,1.75,modelHint,modelHint|-,55,modelHint,modelHint;-,16,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-07|s1:rir":
      "5#-,100,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,97.5,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-07|s1:r+rir":
      "5#-,90,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.25,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.75,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-13|none":
      "5#-,77.5,modelHint,modelHint;-,11,modelHint,modelHint;-,1,modelHint,modelHint|-,72.5,modelHint,modelHint;-,12,modelHint,modelHint;-,1.25,modelHint,modelHint|-,67.5,modelHint,modelHint;-,13,modelHint,modelHint;-,1.5,modelHint,modelHint|-,62.5,modelHint,modelHint;-,14,modelHint,modelHint;-,1.75,modelHint,modelHint|-,62.5,modelHint,modelHint;-,14,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-13|s1:rir":
      "5#-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;1.25,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,6,typed,modelHint;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-25|none":
      "5#-,107.5,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,102.5,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-25|s1:rir":
      "5#-,80,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, Classic|None|2026-01-25|s1:r+rir":
      "5#-,100,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,97.5,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-07|none":
      "5#-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,0.3,modelHint,modelHint|-,75,modelHint,modelHint;-,11,modelHint,modelHint;-,0.75,modelHint,modelHint|-,70,modelHint,modelHint;-,12,modelHint,modelHint;-,1.25,modelHint,modelHint|-,65,modelHint,modelHint;-,13,modelHint,modelHint;-,1.75,modelHint,modelHint|-,60,modelHint,modelHint;-,14,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-07|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,5,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint|-,67.5,modelHint,modelHint;-,11,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-13|none":
      "5#-,85,modelHint,modelHint;-,9,modelHint,modelHint;-,1,modelHint,modelHint|-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,1.25,modelHint,modelHint|-,75,modelHint,modelHint;-,11,modelHint,modelHint;-,1.5,modelHint,modelHint|-,70,modelHint,modelHint;-,12,modelHint,modelHint;-,1.75,modelHint,modelHint|-,70,modelHint,modelHint;-,12,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,6,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,7,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-13|s1:rir":
      "5#-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;1.25,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,6,typed,modelHint;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-25|none":
      "5#-,85,modelHint,modelHint;-,10,modelHint,modelHint;-,2.5,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-25|s1:rir":
      "5#-,82.5,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|Smart Progression|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-07|none":
      "5#-,80,modelHint,modelHint;-,10,modelHint,modelHint;-,0.3,modelHint,modelHint|-,75,modelHint,modelHint;-,11,modelHint,modelHint;-,0.75,modelHint,modelHint|-,70,modelHint,modelHint;-,12,modelHint,modelHint;-,1.25,modelHint,modelHint|-,65,modelHint,modelHint;-,13,modelHint,modelHint;-,1.75,modelHint,modelHint|-,60,modelHint,modelHint;-,14,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-07|s1:w":
      "5#96.25,-,typed,empty;-,5,modelHint,modelHint;-,0.3,modelHint,modelHint|-,95,modelHint,modelHint;-,5,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,5,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,5,modelHint,modelHint;-,1.75,modelHint,modelHint|-,87.5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-07|s1:rir":
      "5#-,97.5,modelHint,modelHint;-,3,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,4,modelHint,modelHint;-,0.75,modelHint,modelHint|-,92.5,modelHint,modelHint;-,4,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,4,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,5,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-07|s1:r+rir":
      "5#-,87.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,0.75,modelHint,modelHint|-,77.5,modelHint,modelHint;-,9,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1.75,modelHint,modelHint|-,67.5,modelHint,modelHint;-,11,modelHint,modelHint;-,2.25,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-13|none":
      "5#-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,1,modelHint,modelHint|-,77.5,modelHint,modelHint;-,11,modelHint,modelHint;-,1.25,modelHint,modelHint|-,72.5,modelHint,modelHint;-,12,modelHint,modelHint;-,1.5,modelHint,modelHint|-,67.5,modelHint,modelHint;-,13,modelHint,modelHint;-,1.75,modelHint,modelHint|-,67.5,modelHint,modelHint;-,13,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-13|s1:w":
      "5#96.25,-,typed,empty;-,6,modelHint,modelHint;-,1,modelHint,modelHint|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-13|s1:rir":
      "5#-,95,modelHint,modelHint;-,6,modelHint,modelHint;1.25,-,typed,empty|-,95,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,90,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,85,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-13|s1:r+rir":
      "5#-,92.5,modelHint,modelHint;6,6,typed,modelHint;1.5,-,typed,empty|-,92.5,modelHint,modelHint;-,6,modelHint,modelHint;-,1.25,modelHint,modelHint|-,87.5,modelHint,modelHint;-,7,modelHint,modelHint;-,1.5,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint|-,82.5,modelHint,modelHint;-,8,modelHint,modelHint;-,1.75,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-25|none":
      "5#-,85,modelHint,modelHint;-,10,modelHint,modelHint;-,2.5,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,80,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,7,modelHint,modelHint;-,2.5,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint|-,95,modelHint,modelHint;-,7,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-25|s1:rir":
      "5#-,82.5,modelHint,modelHint;-,12,modelHint,modelHint;1.25,-,typed,empty|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint|-,82.5,modelHint,modelHint;-,10,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Parity Cable Pull|Linear, by Exposure|None|2026-01-25|s1:r+rir":
      "5#-,102.5,modelHint,modelHint;6,-,typed,empty;1.5,-,typed,empty|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint|-,100,modelHint,modelHint;-,5,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Chin-Up|DUP, By Exposure|Smart Progression|2026-01-25|none":
      "5#-,30,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,25,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,20,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,15,modelHint,modelHint;-,6,modelHint,modelHint;-,4,modelHint,modelHint|-,10,modelHint,modelHint;-,7,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Chin-Up|DUP, By Exposure|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,1,modelHint,modelHint;-,2.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,1,modelHint,modelHint;-,3.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,1,modelHint,modelHint;-,4,modelHint,modelHint|-,85,modelHint,modelHint;-,1,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Chin-Up|DUP, Signature|Smart Progression|2026-01-25|none":
      "5#-,5,modelHint,modelHint;-,5,modelHint,modelHint;-,2.5,modelHint,modelHint|-,0,modelHint,modelHint;-,6,modelHint,modelHint;-,3,modelHint,modelHint|-,0,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,0,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,0,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Chin-Up|DUP, Signature|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,1,modelHint,modelHint;-,2.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,1,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,1,modelHint,modelHint;-,3.5,modelHint,modelHint|-,90,modelHint,modelHint;-,1,modelHint,modelHint;-,3.5,modelHint,modelHint",
  "A|Chin-Up|DUP, By Week|Smart Progression|2026-01-25|none":
      "5#-,30,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,25,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,20,modelHint,modelHint;-,5,modelHint,modelHint;-,3.5,modelHint,modelHint|-,15,modelHint,modelHint;-,6,modelHint,modelHint;-,4,modelHint,modelHint|-,10,modelHint,modelHint;-,7,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Chin-Up|DUP, By Week|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,1,modelHint,modelHint;-,2.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,90,modelHint,modelHint;-,1,modelHint,modelHint;-,3.5,modelHint,modelHint|-,87.5,modelHint,modelHint;-,1,modelHint,modelHint;-,4,modelHint,modelHint|-,85,modelHint,modelHint;-,1,modelHint,modelHint;-,4.5,modelHint,modelHint",
  "A|Chin-Up|Linear, Classic|Smart Progression|2026-01-25|none":
      "5#-,30,modelHint,modelHint;-,3,modelHint,modelHint;-,2.5,modelHint,modelHint|-,25,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,25,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,25,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint|-,25,modelHint,modelHint;-,4,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Chin-Up|Linear, Classic|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,1,modelHint,modelHint;-,2.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Chin-Up|Linear, by Exposure|Smart Progression|2026-01-25|none":
      "5#-,5,modelHint,modelHint;-,10,modelHint,modelHint;-,2.5,modelHint,modelHint|-,0,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,0,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,0,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint|-,0,modelHint,modelHint;-,11,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Chin-Up|Linear, by Exposure|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,1,modelHint,modelHint;-,2.5,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint|-,92.5,modelHint,modelHint;-,1,modelHint,modelHint;-,3,modelHint,modelHint",
  "A|Weighted Plank|DUP, By Exposure|Smart Progression|2026-01-25|none":
      "5#-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|DUP, By Exposure|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|DUP, Signature|Smart Progression|2026-01-25|none":
      "5#-,5,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|DUP, Signature|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,25,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,25,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|DUP, By Week|Smart Progression|2026-01-25|none":
      "5#-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|DUP, By Week|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|Linear, Classic|Smart Progression|2026-01-25|none":
      "5#-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,30,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|Linear, Classic|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|Linear, by Exposure|Smart Progression|2026-01-25|none":
      "5#-,5,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,5,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
  "A|Weighted Plank|Linear, by Exposure|Smart Progression|2026-01-25|s1:w":
      "5#96.25,-,typed,empty;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty|-,96.25,modelHint,modelHint;-,60,modelHint,modelHint;-,-,empty,empty",
};
