import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

import 'exercise_model.dart';
import 'template_model.dart'; // Assuming your template model is in this file
import 'template_utils.dart'; // Import the shared methods

class CreateTemplateScreen extends StatefulWidget {
  final VoidCallback onTemplateCreated; // Callback to refresh template list
  const CreateTemplateScreen({super.key, required this.onTemplateCreated});

  @override
  State<CreateTemplateScreen> createState() => _CreateTemplateScreenState();
}

class _CreateTemplateScreenState extends State<CreateTemplateScreen> {
  final _formKey = GlobalKey<FormState>();
  String _name = '';
  String _day = '';
  final _selectedExercises = <String>[]; // Initialize as empty list
  List<Exercise> exercises = []; // List of available exercises
  // Generate a unique ID (replace with your preferred method)
  final generatedId =
      'template_${DateTime.now().millisecondsSinceEpoch}_${Random().nextInt(1000)}';

  @override
  void initState() {
    super.initState();
    _fetchExercises();
  }

  Future<void> _fetchExercises() async {
    try {
      final querySnapshot =
          await FirebaseFirestore.instance.collection('exercises').get();
      final exerciseList = querySnapshot.docs
          .map((doc) => Exercise(
                id: doc.id,
                name: doc.get('name'),
                bodyPart: doc.get('bodyPart'), // Access the bodyPart field
                category: doc.get('category'), // Access the category field
              ))
          .toList();
      setState(() {
        exercises = exerciseList;
      });
    } catch (error) {
      print("Error fetching exercises: $error");
    }
  }

  final Map<String, String> _exerciseNameMap = {};

  void _handleExerciseSelection(Exercise exercise, bool isSelected) {
    setState(() {
      if (isSelected) {
        _selectedExercises.add(exercise.id);
        _exerciseNameMap[exercise.id] = exercise.name; // Store exercise name
      } else {
        _selectedExercises.remove(exercise.id);
        _exerciseNameMap.remove(exercise.id); // Remove exercise name
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Template'),
        actions: [
          IconButton(
            icon: const Icon(Icons.save), // Or any other icon you prefer
            onPressed: () => _submitTemplate(context),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: const InputDecoration(labelText: 'Template Name'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a name' : null,
                onSaved: (value) => setState(() => _name = value!),
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Day'),
                validator: (value) =>
                    value!.isEmpty ? 'Please enter a name' : null,
                onSaved: (value) => setState(() => _day = value!),
              ),
              Expanded(
                // Ensures remaining space is filled by the list
                child: ListView.builder(
                  shrinkWrap: true,
                  itemCount: exercises.length,
                  itemBuilder: (context, index) {
                    final exercise = exercises[index];
                    return CheckboxListTile(
                      title: Text(exercise.name),
                      value: _selectedExercises.contains(exercise.id),
                      onChanged: (value) =>
                          _handleExerciseSelection(exercise, value!),
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _submitTemplate(BuildContext context) {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      if (_selectedExercises.isEmpty) {
        // Handle empty exercise list, e.g., show an error message
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select at least one exercise')),
        );
        return;
      }

      final newTemplate = Template(
        id: ' ', // Will be generated by Firestore
        name: _name,
        day: _day,
        exercises: _selectedExercises
            .map((id) => _exerciseNameMap[id]!)
            .toList(), // Convert IDs to names
      );

      addTemplateToFirestore(newTemplate, generatedId).then((_) {
        // Handle successful template addition, e.g., show a snackbar
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Template created successfully')),
        );
        widget.onTemplateCreated(); // Call the refresh function
        Navigator.pop(context);
      }).catchError((error) {
        // Handle errors, e.g., show an error message
      });
    }
  }
}
