// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCno2XAn363PbSJqf9qHkRVMO7T4WW6uuI',
    appId: '1:659564418928:ios:7460f78a3d7e1260b4a1b5',
    messagingSenderId: '659564418928',
    projectId: 'goodlift-us-storage',
    storageBucket: 'goodlift-us-storage.firebasestorage.app',
    androidClientId: '659564418928-ohv0gvu4cp4uceg979efs347cj62s842.apps.googleusercontent.com',
    iosClientId: '659564418928-tb6thrajkglrsrmbv1tiu5jbtq2nka6q.apps.googleusercontent.com',
    iosBundleId: 'com.goodlift.razorsedge',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZM7fWijrscBkM2PeMjoWfm8RmHgKyESI',
    appId: '1:659564418928:android:d21ae3148bf008d3b4a1b5',
    messagingSenderId: '659564418928',
    projectId: 'goodlift-us-storage',
    storageBucket: 'goodlift-us-storage.firebasestorage.app',
  );

}