// Regenerates functions/social/search_normalize_vectors.json.
//
// The vector file is the single source of truth that pins the JavaScript
// indexer (functions/social/search_normalize.js) to its Dart query-side twin
// (lib/social/search_normalize.dart). Both test suites read the SAME file, so
// a change to one implementation that is not mirrored in the other fails a
// test instead of quietly degrading search for accented or misspelled names.
//
// The expected values are produced by the JS implementation, which is the
// writer and therefore the authority on what is actually in the index.
//
//   node scripts/gen_search_vectors.js
//
// Run from the functions/ directory. Writing new vectors is a deliberate act:
// review the diff, then run both suites.

'use strict';

const fs = require('fs');
const path = require('path');

const normalize = require('../social/search_normalize');

/// Inputs chosen to exercise each rule the two implementations must share:
/// composed accents, atomic letters NFD does not decompose, multi-character
/// expansions, punctuation, case, whitespace collapse and empty input.
const NORMALIZE_CASES = [
  'Renée',
  "  Renée   O'Brien-Smith ",
  'Jonh_Doe',
  'MÜLLER',
  'Łukasz Ćwik',
  'Søren Kierkegård',
  'Straße',
  'Ægir Þorsson',
  'Jean-Luc  Picard',
  'œuvre',
  'éclair',
  // The same word typed with a DECOMPOSED accent (e + U+0301). Arrives from
  // dictation and pasted text, and must land on the same string.
  'éclair',
  'JOHN',
  'a',
  '   ',
  '',
  'user.name+42',
  'Ösgür  İlhan',
  'naïve café',
  'Zoë  ',
  '🏋️ lifter',
  'ANNA-MARIA de la Cruz',
];

const TOKEN_IDENTITIES = [
  {
    username: 'Jonh_Doe',
    firstName: 'John',
    lastName: 'Doe',
    displayName: 'John Doe',
  },
  {
    username: 'renee',
    firstName: 'Renée',
    lastName: 'Larsson',
    displayName: 'Renée L',
  },
  {
    username: 'lukasz',
    firstName: 'Łukasz',
    lastName: 'Ćwik',
    displayName: 'Łukasz Ćwik',
  },
];

const QUERY_GRAM_CASES = ['john', 'jo', 'renee', 'a', 'Renée', ''];

function main() {
  const payload = {
    note:
      'Generated by functions/scripts/gen_search_vectors.js. Shared by ' +
      'functions/test/social_search_normalize.test.js and ' +
      'test/social_search_normalize_test.dart to pin the JS indexer to its ' +
      'Dart query-side twin. Do not hand-edit.',
    normalize: NORMALIZE_CASES.map((input) => ({
      input,
      expected: normalize.normalizeText(input),
    })),
    compact: NORMALIZE_CASES.map((input) => ({
      input,
      expected: normalize.compactText(input),
    })),
    tokens: TOKEN_IDENTITIES.map((identity) => ({
      identity,
      expected: normalize.buildSearchTokens(identity),
    })),
    queryGrams: QUERY_GRAM_CASES.map((input) => ({
      input,
      expected: normalize.queryGrams(input),
    })),
  };

  const target = path.join(
    __dirname,
    '..',
    'social',
    'search_normalize_vectors.json',
  );
  fs.writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
  process.stdout.write(
    `wrote ${payload.normalize.length} normalize, ` +
      `${payload.tokens.length} token, ` +
      `${payload.queryGrams.length} gram vectors to ${target}\n`,
  );
}

main();
